#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "${ROOT}/ota-lib.sh" ]]; then
  # Packaged release path.
  # shellcheck source=/dev/null
  source "${ROOT}/ota-lib.sh"
elif [[ -f "${ROOT}/reactor-edge-ota-lib.sh" ]]; then
  # Repository deploy/ path.
  # shellcheck source=/dev/null
  source "${ROOT}/reactor-edge-ota-lib.sh"
elif [[ -f "/opt/reactor-edge/ota-lib.sh" ]]; then
  # Installed root path.
  # shellcheck source=/dev/null
  source "/opt/reactor-edge/ota-lib.sh"
else
  echo "missing ota-lib.sh" >&2
  exit 1
fi

usage() {
  cat <<'EOF'
Install a ReactorOS release package into the inactive application slot.

Usage:
  sudo ota-update.sh <release.tar.gz> [options]

Options:
  --sha256 <file>              Verify package with an explicit sha256 sidecar.
  --allow-missing-checksum     Permit update when no sha256 sidecar exists.
  --confirm-unsafe-no-checksum Required with --allow-missing-checksum.
  --dry-run                    Validate the package and field state without switching slots.
  --force                      Bypass production busy/emergency checks.
  --confirm-maintenance-window Required with --force.
  --skip-backup                Do not create a pre-update SQLite snapshot.
  --confirm-skip-backup        Required with --skip-backup.
  --health-attempts <n>        Health attempts after switching, default 12.
  --health-interval <seconds>  Delay between attempts, default 5.
  --required-passes <n>        Consecutive successful health checks, default 3.
  -h, --help                   Show this help.

The package must be the tar.gz generated by the PC-side release build. The
script never writes into the running slot; it stages the inactive slot, switches
/opt/reactor-edge/current, verifies health, and rolls back on failure.
With --dry-run, the script validates the same package, checksum, busy-state,
disk-space, backup availability, slot integrity, and candidate contents, then
exits without changing current/previous, systemd units, or database snapshots.
EOF
}

PACKAGE=""
SHA256_FILE=""
ALLOW_MISSING_CHECKSUM=0
CONFIRM_UNSAFE_NO_CHECKSUM=0
DRY_RUN=0
FORCE=0
CONFIRM_MAINTENANCE_WINDOW=0
SKIP_BACKUP=0
CONFIRM_SKIP_BACKUP=0
HEALTH_ATTEMPTS=12
HEALTH_INTERVAL=5
REQUIRED_PASSES=3
OTA_PRE_SWITCH_STATUS_STARTED=0
OTA_PRE_SWITCH_REJECTED_ON_EXIT=0

ota_exit_hook() {
  local rc="${1:-0}"
  if [[ "$rc" -ne 0 && "$OTA_PRE_SWITCH_STATUS_STARTED" -eq 1 && "$OTA_PRE_SWITCH_REJECTED_ON_EXIT" -eq 1 ]]; then
    clear_ota_service_start_allowed
    write_ota_state \
      "rejected_before_switch" \
      "" \
      "OTA update failed before switching current slot; current slot remains active" \
      "${PACKAGE:-}" \
      "${FROM_VERSION:-}" \
      "${TARGET_VERSION:-}" \
      "${FROM_GIT:-}" \
      "${TARGET_GIT:-}" >/dev/null 2>&1 || true
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --sha256)
      SHA256_FILE="${2:-}"
      [[ -n "$SHA256_FILE" ]] || die "--sha256 requires a file"
      shift 2
      ;;
    --allow-missing-checksum)
      ALLOW_MISSING_CHECKSUM=1
      shift
      ;;
    --confirm-unsafe-no-checksum)
      CONFIRM_UNSAFE_NO_CHECKSUM=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --force)
      FORCE=1
      shift
      ;;
    --confirm-maintenance-window)
      CONFIRM_MAINTENANCE_WINDOW=1
      shift
      ;;
    --skip-backup)
      SKIP_BACKUP=1
      shift
      ;;
    --confirm-skip-backup)
      CONFIRM_SKIP_BACKUP=1
      shift
      ;;
    --health-attempts)
      HEALTH_ATTEMPTS="${2:-}"
      shift 2
      ;;
    --health-interval)
      HEALTH_INTERVAL="${2:-}"
      shift 2
      ;;
    --required-passes)
      REQUIRED_PASSES="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      if [[ -z "$PACKAGE" ]]; then
        PACKAGE="$1"
        shift
      else
        die "unexpected argument: $1"
      fi
      ;;
  esac
done

[[ -n "$PACKAGE" ]] || {
  usage >&2
  exit 2
}
validate_health_args "$HEALTH_ATTEMPTS" "$HEALTH_INTERVAL" "$REQUIRED_PASSES"
require_confirmed_dangerous_option "--allow-missing-checksum" "--confirm-unsafe-no-checksum" "$ALLOW_MISSING_CHECKSUM" "$CONFIRM_UNSAFE_NO_CHECKSUM"
require_confirmed_dangerous_option "--force" "--confirm-maintenance-window" "$FORCE" "$CONFIRM_MAINTENANCE_WINDOW"
require_confirmed_dangerous_option "--skip-backup" "--confirm-skip-backup" "$SKIP_BACKUP" "$CONFIRM_SKIP_BACKUP"

require_root
ensure_runtime_dirs
require_ota_update_commands
acquire_ota_lock

PACKAGE="$(readlink -f "$PACKAGE")"
[[ -f "$PACKAGE" ]] || die "release package not found: $PACKAGE"
case "$PACKAGE" in
  *.tar.gz|*.tgz) ;;
  *) die "release package must be .tar.gz or .tgz: $PACKAGE" ;;
esac

OTA_PRE_SWITCH_STATUS_STARTED=1
OTA_PRE_SWITCH_REJECTED_ON_EXIT=1
ensure_cleanup_trap

write_ota_state "downloading" "" "" "$PACKAGE"
log "using local release package: $PACKAGE"

if [[ -z "$SHA256_FILE" ]]; then
  if [[ -f "${PACKAGE}.sha256" ]]; then
    SHA256_FILE="${PACKAGE}.sha256"
  elif [[ -f "${PACKAGE%.tgz}.sha256" ]]; then
    SHA256_FILE="${PACKAGE%.tgz}.sha256"
  fi
fi

write_ota_state "verifying" "" "" "$PACKAGE"
if [[ -n "$SHA256_FILE" ]]; then
  SHA256_FILE="$(readlink -f "$SHA256_FILE")"
  log "verifying package sha256: $SHA256_FILE"
  verify_sha256_for_package "$PACKAGE" "$SHA256_FILE"
elif [[ "$ALLOW_MISSING_CHECKSUM" -eq 1 ]]; then
  log "WARNING: checksum sidecar missing; proceeding because --allow-missing-checksum was explicitly confirmed"
else
  die "missing sha256 sidecar; provide --sha256 or use --allow-missing-checksum --confirm-unsafe-no-checksum only for lab recovery"
fi
write_ota_state "verified" "" "" "$PACKAGE"

check_not_busy "$FORCE"
ensure_space_for_package "$PACKAGE"
validate_tar_package "$PACKAGE"
TARGET_SLOT="$(inactive_slot_name)"
PREVIOUS_PATH="$(optional_current_slot_path)"
FROM_VERSION=""
FROM_GIT=""
TARGET_VERSION=""
TARGET_GIT=""
if [[ -n "$PREVIOUS_PATH" ]]; then
  FROM_VERSION="$(release_version_from_dir "$PREVIOUS_PATH")"
  FROM_GIT="$(release_git_from_dir "$PREVIOUS_PATH")"
fi
read_release_metadata_from_package "$PACKAGE" "$TARGET_SLOT"
TARGET_VERSION="$RELEASE_PACKAGE_VERSION"
TARGET_GIT="$RELEASE_PACKAGE_GIT"

if [[ "$DRY_RUN" -eq 1 ]]; then
  check_pre_update_backup_available "$SKIP_BACKUP"
  dry_run_release_candidate_validation "$PACKAGE" "$TARGET_SLOT"
  write_ota_state "dry_run_passed" "$TARGET_SLOT" "" "$PACKAGE" "$FROM_VERSION" "$TARGET_VERSION" "$FROM_GIT" "$TARGET_GIT"
  log "dry-run passed for inactive slot ${TARGET_SLOT}; no slot switch performed"
  exit 0
fi

run_pre_update_backup "$SKIP_BACKUP"
write_ota_state "backup_done" "" "" "$PACKAGE" "$FROM_VERSION" "$TARGET_VERSION" "$FROM_GIT" "$TARGET_GIT"

TARGET_DIR="$(slot_path "$TARGET_SLOT")"
EXTRACT_DIR="${SLOTS_DIR}/.${TARGET_SLOT}.extract.$$"
STAGE_DIR="${SLOTS_DIR}/${TARGET_SLOT}.tmp.$$"
register_safe_remove_cleanup "$EXTRACT_DIR" "$SLOTS_DIR"
register_safe_remove_cleanup "$STAGE_DIR" "$SLOTS_DIR"

write_ota_state "staged" "$TARGET_SLOT" "extracting" "$PACKAGE" "$FROM_VERSION" "$TARGET_VERSION" "$FROM_GIT" "$TARGET_GIT"
log "staging package into inactive slot ${TARGET_SLOT}"
safe_remove_path "$EXTRACT_DIR" "$SLOTS_DIR" 2>/dev/null || true
safe_remove_path "$STAGE_DIR" "$SLOTS_DIR" 2>/dev/null || true
extract_release_candidate_to_stage "$PACKAGE" "$EXTRACT_DIR" "$STAGE_DIR"
safe_remove_path "$TARGET_DIR" "$SLOTS_DIR" 2>/dev/null || true
mv "$STAGE_DIR" "$TARGET_DIR"
flush_ota_disk "slot ${TARGET_SLOT} replacement"
validate_slot_dir "$TARGET_DIR"

if [[ -n "$PREVIOUS_PATH" ]]; then
  atomic_symlink "$PREVIOUS_PATH" "$PREVIOUS_LINK"
fi
OTA_PRE_SWITCH_REJECTED_ON_EXIT=0
write_ota_state "switching" "$TARGET_SLOT" "" "$PACKAGE" "$FROM_VERSION" "$TARGET_VERSION" "$FROM_GIT" "$TARGET_GIT"
log "switching current slot to ${TARGET_SLOT}"
stop_runtime_services
install_root_ota_tools_from_slot "$TARGET_DIR"
log "installing systemd units from slot ${TARGET_SLOT}"
install_systemd_units_from_slot "$TARGET_DIR"
atomic_symlink "$TARGET_DIR" "$CURRENT_LINK"
sync_compat_links
write_ota_state "health_checking" "$TARGET_SLOT" "" "$PACKAGE" "$FROM_VERSION" "$TARGET_VERSION" "$FROM_GIT" "$TARGET_GIT"
if start_runtime_services && health_check_loop "$HEALTH_ATTEMPTS" "$HEALTH_INTERVAL" "$REQUIRED_PASSES"; then
  write_ota_state "committed" "$TARGET_SLOT" "" "$PACKAGE" "$FROM_VERSION" "$TARGET_VERSION" "$FROM_GIT" "$TARGET_GIT"
  log "OTA committed on slot ${TARGET_SLOT}"
  exit 0
fi

log "new slot ${TARGET_SLOT} failed health checks; attempting rollback"
write_ota_state "rolling_back" "$TARGET_SLOT" "new slot health check failed" "$PACKAGE" "$FROM_VERSION" "$TARGET_VERSION" "$FROM_GIT" "$TARGET_GIT"
if [[ -z "$PREVIOUS_PATH" || ! -d "$PREVIOUS_PATH" ]]; then
  enter_ota_failed_state "$TARGET_SLOT" "new slot failed and no previous slot exists" "$PACKAGE" "$FROM_VERSION" "$TARGET_VERSION" "$FROM_GIT" "$TARGET_GIT"
  die "new slot failed and no previous slot exists"
fi

stop_runtime_services
log "restoring systemd units from previous slot"
install_systemd_units_from_slot "$PREVIOUS_PATH"
atomic_symlink "$PREVIOUS_PATH" "$CURRENT_LINK"
sync_compat_links
install_root_ota_tools_from_slot "$PREVIOUS_PATH"

if start_runtime_services && health_check_loop "$HEALTH_ATTEMPTS" "$HEALTH_INTERVAL" "$REQUIRED_PASSES"; then
  local_previous_slot="$(slot_name_from_path "$PREVIOUS_PATH")"
  write_ota_state "rolled_back" "$local_previous_slot" "new slot ${TARGET_SLOT} failed health check" "$PACKAGE" "$TARGET_VERSION" "$FROM_VERSION" "$TARGET_GIT" "$FROM_GIT"
  log "rollback to previous slot succeeded"
  exit 1
fi

enter_ota_failed_state "$TARGET_SLOT" "rollback health check failed" "$PACKAGE" "$FROM_VERSION" "$TARGET_VERSION" "$FROM_GIT" "$TARGET_GIT"
die "rollback health check failed; keep device in manual maintenance"
